### ISSUE TITLE
`C`/`C++` API test strategy

### ISSUE THREAD

**Issue by foundrytom** [TheFoundryVisionmongers/OpenAssetIO#196]
## What

Determine how we are going to write and test the `C` API surface - the existing approach of using the `pytest` tests to check `Python` and `C++` would miss the `C` API.

In addition, as we have built out the `C++` API, we now have functionality that can't be covered from python (as the types are bound to native types in `pybind`).

An ideal solution would facilitate the testing of both `C++` and `C` APIs as required.

Timeboxed to 1 day

## ACs

- Proposal for `C` and `C++` testing that ensures code paths not testable through the `pytest` checks are covered.
- Uses industry standard testing framework/library if appropriate, that are readily available for an OSS project and well understood by the target audience.
- High-level estimate of effort/work to be done to implement.

**Comment by foundrytom** [comment]
Came across this (not read fully yet): https://p403n1x87.github.io/running-c-unit-tests-with-pytest.html

**Comment by fnRaihanKibria** [comment]
# C++ unit testing survey

Following related projects have tests for their C++ sources.

## USD

Uses a custom made solution rather than external libraries, with USD-specific macros for assertions, e.g. TF_AXIOM and TF_VERIFY.

Usage example [here](https://github.com/PixarAnimationStudios/USD/blob/release/pxr/usd/usd/testenv/testUsdUsdzResolver.cpp)

## OpenTimelineIO (an ASWF project)

Uses a custom solution consisting of a small test set container class and some assertion macros. They implemented some special asserts for floating point comparisons with a tolerance (this kind of functionality is also available in testing frameworks, e.g. [Catch2](https://github.com/catchorg/Catch2/blob/devel/docs/assertions.md#floating-point-comparisons)).

Usage example [here](https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/main/tests/test_clip.cpp)

## OpenColorIO (an ASWF project)

Uses a custom solution, the [OpenImageIO test framework](https://github.com/OpenImageIO/oiio/blob/master/src/include/OpenImageIO/unittest.h).

Usage example [here](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/tests/cpu/ColorSpace_tests.cpp)

## OpenEXR (an ASWF project)

Uses a custom solution that seems to rely on standard assert.h a lot.

Usage example [here](https://github.com/AcademySoftwareFoundation/openexr/blob/main/src/test/OpenEXRTest/testConversion.cpp)

## OpenVDB (an ASWF project)

Uses Google Test framework.

Usage example [here](https://github.com/AcademySoftwareFoundation/openvdb/blob/master/openvdb/openvdb/unittest/TestAttributeArray.cc)

# Drawbacks of custom solutions

- Requires newcomer devs to the project to learn custom approach to testing.
- Custom solutions often require explicit registering of tests, whereas dedicated frameworks usually implicitly register their tests, leading to less cluttered code.
- Have to write asserting commands which add yet more new things to learn.

# Popular unit test frameworks

Two projects stand out when reading about C++ unit test frameworks online: Google Test and Catch2.

## Google Test

https://github.com/google/googletest

- Very mature, widely used and well supported.
- Includes Google Mock library.

Example:

    TEST(FactorialTest, HandlesZeroInput) { // TestSuiteName, TestName
      EXPECT_EQ(Factorial(0), 1);
    }

    TEST(FactorialTest, HandlesPositiveInput) {
      EXPECT_EQ(Factorial(1), 1);
      EXPECT_EQ(Factorial(8), 40320);
    }

A fixture class:

    class QueueTest : public ::testing::Test {
    protected:
      void SetUp() override {
        q1_.Enqueue(1);
      }

      // void TearDown() override {}

      Queue<int> q0_;
      Queue<int> q1_;
    };

    TEST_F(QueueTest, IsEmptyInitially) {
      EXPECT_EQ(q0_.size(), 0);
    }

    TEST_F(QueueTest, DequeueWorks) {
      int* n = q0_.Dequeue();
      EXPECT_EQ(n, nullptr);

      n = q1_.Dequeue();
      ASSERT_NE(n, nullptr);
      EXPECT_EQ(*n, 1);
      EXPECT_EQ(q1_.size(), 0);
      delete n;
    }

## Catch2

https://github.com/catchorg/Catch2

- Newer than Google Test, but also very widely used.
- A single header to include.
- Very readable testing code using sections where normally fixtures would be required (though traditional fixtures are also supported).
- Expressive matchers (use normal comparison instead of macros arguments).
- Does not contain a mocking library but is compatible with GoogleMock, [trompeloeil](https://github.com/rollbear/trompeloeil) etc.

Example:

    // free form test name and, optionally, one or more tags
    TEST_CASE( "Factorials are computed", "[factorial]" ) {
        REQUIRE( Factorial(0) == 1 );
        REQUIRE( Factorial(1) == 1 );
        REQUIRE( Factorial(2) == 2 );
        REQUIRE( Factorial(3) == 6 );
        REQUIRE( Factorial(10) == 3628800 );
    }

The REQUIRE macro accepts a boolean expression, and uses expression templates to internally decompose it, so that it can be individually stringified on test failure. There are more macros provided, e.g. checking that an expression throws an exception is done with the REQUIRE_THROWS macro.

    TEST_CASE( "vectors can be sized and resized", "[vector]" ) {
        std::vector<int> v( 5 );

        REQUIRE( v.size() == 5 );
        REQUIRE( v.capacity() >= 5 );

        SECTION( "resizing bigger changes size and capacity" ) {
            v.resize( 10 );

            REQUIRE( v.size() == 10 );
            REQUIRE( v.capacity() >= 10 );
        }
        SECTION( "resizing smaller changes size but not capacity" ) {
            v.resize( 0 );

            REQUIRE( v.size() == 0 );
            REQUIRE( v.capacity() >= 5 );
        }
    }

Idiomatic Catch2 tests use sections to share setup and teardown code between test code. For each SECTION the TEST_CASE is executed from the start.

    SECTION( "reserving bigger changes capacity but not size" ) {
        v.reserve( 10 );

        REQUIRE( v.size() == 5 );
        REQUIRE( v.capacity() >= 10 );
        SECTION( "reserving down unused capacity does not change capacity" ) {
            v.reserve( 7 );
            REQUIRE( v.size() == 5 );
            REQUIRE( v.capacity() >= 10 );
        }
    }

Section can also be nested, in which case the parent section can be entered multiple times, once for each leaf section.

# Summary

We should definitely use an established framework instead of a custom solution. Of the popular solutions, Catch2 seems the better choice in particular due to its expressive syntax.

**Comment by foundrytom** [comment]
Great work @fnRaihanKibria  - what are your thoughts on [the migration to Catch2 v3](https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md#top)?

**Comment by fnRaihanKibria** [comment]
> Great work @fnRaihanKibria - what are your thoughts on [the migration to Catch2 v3](https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md#top)?

The v3 version is not yet available on the [conan repo](https://conan.io/center/catch2) but presumably will be there soon. For now I think it's safe to stick to v2 since the syntax itself isn't going to change, and then upgrade to v3 once available. If it's packaged up correctly then the change should require not much more than renaming some includes. I would expect the new static library to be included in the CMake target for linking.

**Comment by foundrytom** [comment]
Postponing investigation into mock lib choice until we need one, going with Catch2 for now.
